if(EXISTS "/Volumes/DockDrive/research/darkome/DataTable/build-release/tests/DataTableTests[1]_tests.cmake")
  include("/Volumes/DockDrive/research/darkome/DataTable/build-release/tests/DataTableTests[1]_tests.cmake")
else()
  add_test(DataTableTests_NOT_BUILT DataTableTests_NOT_BUILT)
endif()
